name: Build

on: [ push,pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew shadowJar

      - name: Upload build artifacts velocity
        uses: actions/upload-artifact@v3
        with:
          name: velocity-build
          path: gameman-velocity/build/libs
